#!/usr/bin/env bash
# requires a domain and accepts optional subdomain name passed in
# audits domain or specific subdomain and prints selected info to stdout
# Function to display subdomain information
display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    # Get DNS records for the specified subdomain
    records=$(dig +short "$subdomain.$domain")

    if [ -z "$records" ]; then
        echo "The subdomain $subdomain is not configured."
    else
        echo "The subdomain $subdomain is a $(echo "$records" | awk '{print $4}') record and points to $(echo "$records" | awk '{print $1}')."
    fi
}

# Main script
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"

# Display information for specific subdomain (if provided)
if [ $# -eq 2 ]; then
    subdomain="$2"
    display_subdomain_info "$domain" "$subdomain"
else
    # Display information for default subdomains
    display_subdomain_info "$domain" "www"
    display_subdomain_info "$domain" "lb-01"
    display_subdomain_info "$domain" "web-01"
    display_subdomain_info "$domain" "web-02"
fi
