#!/usr/bin/env bash
# Find the PID of the 4-to_infinity_and_beyond process
process_pid=$(pgrep 4-to_infinity_and_beyond)

# Check if the process is running
if [ -n "$process_pid" ]; then
    # Send a SIGTERM signal to gracefully stop the process
    kill "$process_pid"
    echo "Terminated"
fi
