#!/usr/bin/env bash
#Bash script that configures an Ubuntu serve

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: 0-change_your_home_IP {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the argument
ip_address="$1"

# Ping the IP address 5 times
# Configure /etc/hosts to set localhost to 127.0.0.2 and facebook.com to 8.8.8.8
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
