#!/usr/bin/env bash
# mode
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/nginx.conf
chmod -R 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
